### ISSUE TITLE
If set position 35,0. The screen will be positioned in an angle.

### ISSUE THREAD

**Issue by wallacepost** [howm/homebridge-vogels-motionmount#29]
If set position 35,0. The screen will be positioned in an angle.

**Comment by momsse** [comment]
Hi @wallacepost,

I encourage you to try the last version of the plugin, it use a `TV` accessory instead of switches and will use the presets you saved in the official app.

**Upgrading from `v0.x.x` to `v1.x.x` require to remove the `~/.homebridge/persist` (or Menu -> Help -> Reset Connection with Hoobs).**

 ![Alt text](https://raw.githubusercontent.com/howm/homebridge-vogels-motionmount/master/screens/motionmount-app.png?raw=true "Motion mount official app") ![Alt text](https://raw.githubusercontent.com/howm/homebridge-vogels-motionmount/master/screens/tv-accessory.png?raw=true "TV accessory")

**Comment by wallacepost** [comment]
> Hi @wallacepost,
> 
> I encourage you to try the last version of the plugin, it use a `TV` accessory instead of switches and will use the presets you saved in the official app.
> 
> **Upgrading from `v0.x.x` to `v1.x.x` require to remove the `~/.homebridge/persist` (or Menu -> Help -> Reset Connection with Hoobs).**
> 
> ![Alt text](https://raw.githubusercontent.com/howm/homebridge-vogels-motionmount/master/screens/motionmount-app.png?raw=true) ![Alt text](https://raw.githubusercontent.com/howm/homebridge-vogels-motionmount/master/screens/tv-accessory.png?raw=true)



> Hi @wallacepost,
> 
> I encourage you to try the last version of the plugin, it use a `TV` accessory instead of switches and will use the presets you saved in the official app.
> 
> **Upgrading from `v0.x.x` to `v1.x.x` require to remove the `~/.homebridge/persist` (or Menu -> Help -> Reset Connection with Hoobs).**
> 
> ![Alt text](https://raw.githubusercontent.com/howm/homebridge-vogels-motionmount/master/screens/motionmount-app.png?raw=true) ![Alt text](https://raw.githubusercontent.com/howm/homebridge-vogels-motionmount/master/screens/tv-accessory.png?raw=true)

It works great now with v1.x.x
Good work mate!👍
