### ISSUE TITLE
mont doesnt move when settings changed in homekit

### ISSUE THREAD

**Issue by SSMARTREPAIR** [howm/homebridge-vogels-motionmount#70]
Here is the log:
[homebridge.log](https://github.com/howm/homebridge-vogels-motionmount/files/6182316/homebridge.log)

**Comment by momsse** [comment]
Hi @SSMARTREPAIR,

It seems that the device running the `homebridge` / `hoobs` with this plugin does not receive any move actions. You should see something like this in your logs:

```log
25/03/2021 à 12:42:55 [MotionMountDynamicPlatform] [moveToPosition] Going to Kitchen
25/03/2021 à 12:42:55 [MotionMountDynamicPlatform] [getPeripheral] Connecting ...
25/03/2021 à 12:42:55 [MotionMountDynamicPlatform] [getPeripheral] Connection established, rssi = -73
25/03/2021 à 12:42:55 [MotionMountDynamicPlatform] [moveToPosition] Getting characteristics ...
...
```

Since bluetooth connectivity between the TV mount and the homebridge device seems good I would probably check if there is connectivity issues between the `homebridge` device and your homekit hub. Wish you good luck.
